---
development:
  dialect: postgres
  database: fmm-db
  user: fmm-user
  password: fmm-password
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/backend_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/backend_production?sslmode=disable"}}
