version: '3.5'

services:
  postgres:
    container_name: fmm-db-container
    image: postgres
    environment:
      POSTGRES_USER: fmm-user
      POSTGRES_PASSWORD: fmm-password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:

volumes:
    postgres:
